### PR TITLE
implement bindings and un-bindings

### PR DESCRIPTION
**Pull request by Gsantomaggio**

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@lukebakken, the PR is ready to review ( if you can).

I created a [file for testing ](https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client/pull/19/files#diff-65026b252de7ac358807e60d6c39ac30c229e0e867ca6682f696efd8a5cf3836)the bindings trying to cover all the cases with and without bindings arguments.

**Review by lukebakken — COMMENTED** [review]
Check out my latest two commits 😸

**Comment by Gsantomaggio** [comment]
Thanks @lukebakken
I like the idea of aggregating the BindingSpecification, even if the old version was the same as the Java AMQP Client.
Old version:
```csharp
 var args = new Dictionary<string, object>() { { "k", "v" } };
        await management.Binding().SourceExchange(source)
            .DestinationQueue(destination)
            .Key(key) /
            .Arguments(args)
            .Bind();

        await management.Unbind().SourceExchange(source).DestinationQueue(destination).Key(key).Arguments(args)
            .UnBind();
```

That is similar to java:
```java
management.exchange().name("e").type(DIRECT).declare();
                management.binding().sourceExchange("e").destinationQueue("q").
                        key("k").arguments(s).bind();


                management.unbind().sourceExchange("e")
                        .destinationQueue("q").key("k").arguments(s).unbind();
```



New version with [your commit](https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client/pull/19/commits/4aac70756e5143db30ce8f1e23505854ae39532f) :


```csharp
var arguments = new Dictionary<string, object> { { key1, value1 }, { key2, value2 } };
await management.CreateBindingSpecification().SourceExchange("exchange_bindings_with_arguments")
            .DestinationQueue("queue_bindings_with_arguments")
            .Key("key")
            .Arguments(arguments)
            .Bind();



await management.CreateBindingSpecification().SourceExchange("exchange_bindings_with_arguments")
            .DestinationQueue("queue_bindings_with_arguments")
            .Key("key").Arguments(arguments).Unbind();
```
That is far from the Java AMQP client.


I don't have a strong opinion on it; what matters is having the same API for Java and .NET.

We have two ways:
 1-  restore the old .NET API Version 
 2- change the Java API

Let me know what you think @acogoluegnes

**Comment by lukebakken** [comment]
I'll revert the naming change. I think it's unnecessary to duplicate an interface just for a different method.

**Pull request merged**
