### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by lukebakken**
* Add solution items
* Use `default` `LangVersion`

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
Do we want to support only .8 ?

**Comment by lukebakken** [comment]
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

I was having issues with tests running correctly with all three TFMs in the projects. I'll look into adding `net6.0` and `net7.0` back.

Note that if we wanted to support as many versions of .NET, we'd do what AmqpNet.Core does -
https://www.nuget.org/packages/AMQPNetLite.Core#supportedframeworks-body-tab

**Comment by lukebakken** [comment]
@Gsantomaggio I'm currently seeing how much of a pain supporting `netstandard2.0` is, like we do with the AMQP 0.9.1 .NET client.

**Comment by Gsantomaggio** [comment]
@lukebakken I don't have any strong opinion on support versions >= net.8 
I asked just because if we want to support only >= 8 we can remove https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client/blob/main/Directory.Packages.props#L22 `System.Diagnostics.DiagnosticSource"` an use the new .NET 8 library for the metrics: https://www.mytechramblings.com/posts/getting-started-with-opentelemetry-metrics-and-dotnet-part-1/

**Review by Gsantomaggio — APPROVED** [review]
Thank you @lukebakken 😃

**Pull request merged**
