### PR TITLE
Enable verbose logging of when a test starts and stops

### LINKED ISSUE #87: Fix GitHub actions timeouts
GHA test runs frequently freeze and eventually time out, on both Windows and Ubuntu runners.

Example:
https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client/actions/runs/11725939742

### PR DESCRIPTION
**Pull request by lukebakken**
Hopefully it will show which test(s) freeze in GHA

Fixes #87

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
Of course, now it works without problems :)

**Comment by lukebakken** [comment]
Of course. I've been able to reproduce a _different_ hang locally, where all of the tests run but the test host does not exit as expected 🤔

**Comment by lukebakken** [comment]
I commented-out the connection recovery test suite and haven't been able to repro, so 🙏 ... that's where I should look...

**Comment by lukebakken** [comment]
@Gsantomaggio there isn't anything earth-shattering here. I don't know why the test suite has run successfully _every_ time.

**Pull request merged**
